<?php use Application\Controller\CommonController;
?>
<div class="internal-banner">
	<img alt="" src="<?php echo CommonController::getImage($this->banner->bannerImg);?>" class="img-responsive">
</div>
<div class="container page-title"><span><?php echo $this->sectionInfo->sectionTitle?></span></div>	
		<div class="container-fluid internal">		
		
		<div class="row news-row">
		<?php $c=1;foreach ($this->news as $row){
			$evenOdd = '';
		if ($c % 2 == 0){
		$evenOdd = 'odd';
		}
			?>
<div class="<?php echo $evenOdd?>">		
			<div class="container news-col">
				<div class="news-image"><img alt="" src="<?php echo CommonController::getImage($row->tbNewsImg);?>"> </div>
				<div class="news-title-date">
				<div class="news-date "><?php echo date("M d, Y", strtotime($row->tbNewsDate));?></div>
				<div class="news-title"><?php echo $row->tbNewsTitle?></div>
				</div>
				<div class="news-desc"><?php echo CommonController::StripText($row->tbNewsDetails, 0, 247, true, true)?>
				<div class="readmore news-more"><a href="<?php echo MAIN_URL.'news-details/'.$row->tbNewsId?>">READ MORE</a></div>
				</div>			
			</div>
			
			</div>
			<?php $c++;}?>
			
		
		</div>
			
		
			</div>
			