<nav class="navbar navbar-inverse customnav <?php echo $this->home?>">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <a class="navbar-brand" href="<?php echo MAIN_URL?>"><img src="images/logo-sm.png"></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
<!--       <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#">Page 1</a></li>
        <li><a href="#">Page 2</a></li> 
        <li><a href="#">Page 3</a></li> 
      </ul> -->
      <ul class="nav navbar-nav navbar-right">
        <li><a href="<?php echo MAIN_URL.'about'?>">About Plumbers</a></li>
        <li><a href="<?php echo MAIN_URL.'services'?>">Services</a></li>
        
        
    <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Projects
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="<?php echo MAIN_URL.'projects/0'?>">Old Projects</a></li>
          <li><a href="<?php echo MAIN_URL.'projects/1'?>">Upcoming Projects</a></li>
        </ul>
      </li>
        
        
        
        
        <!--  <li><a href="<?php //echo MAIN_URL.'products'?>">Products</a></li>-->
        <li><a href="<?php echo MAIN_URL.'news'?>">News/Events</a></li>
        <li><a href="<?php echo MAIN_URL.'contact'?>">Contact us</a></li>
        
        <li class="search-list">
        <div class="search-div">
        <form action="<?php echo MAIN_URL.'search'?>" method="GET">
        <input type="text" class="search" name="keyword">
        <!-- <i class="fa fa-envelope-o"></i> -->
        </form>
        </div>
        </li>
        
      </ul>
    </div>
  </div>
</nav>