<?php 
$metaTitle = 'Plumbers';
$metaDesc = "Plumbers - Professional Plumbing Solutions is providing the best plumbing solutions. Our friendly and professional staff is always ready to detect the problem, and explain what needs to be done to fix it Our highly experienced team is ready to troubleshoot your system, identify the problem, and repair it instantly leaving your place clean and neat.";
$keywords = 'Plumbers, Lebanon, Plumbers in Lebanon, plumbing services in lebanon, maintenance, Leaks and Sewage Backups, Sewer Line Repair, Diagnosis & Checkups, System Maintenance & Cleaning, pipes';
if($this->metaTitle){
    $metaTitle .= ' - '.$this->metaTitle;
}
if($this->metaDesc){
    $metaDesc = $this->metaDesc;
}
?>
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title><?php echo $metaTitle;?></title>
        <base href="<?php echo BASE_URL?>">
        <link rel="icon" type="image/png" href="images/favicon.png" />
        <meta name="description" content="<?php echo trim(strip_tags($metaDesc));?>">
        <meta name="robots" content="none">
        <meta name="keywords" content="<?php echo $keywords; ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">        
        <script src="js/jquery-1.12.0.min.js"></script>
        <link rel="apple-touch-icon" href="apple-touch-icon.png">
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <link rel="stylesheet" href="css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="js/jquery.bxslider/jquery.bxslider.css">
        <link rel="stylesheet" href="js/alertify.js/alertify.core.css">
        <link rel="stylesheet" href="js/alertify.js/alertify.default.css">
        <link rel="stylesheet" href="css/main.css">
        <link rel="stylesheet" href="css/responsive.css">
        <link rel="stylesheet" href="css/fonts.css">
        <link rel="stylesheet" href="fonts/font-awesome-4.5.0/css/font-awesome.min.css">

        <script src="js/modernizr-2.8.3-respond-1.4.2.min.js"></script>
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        
        <div class="ajax-loader"> <img alt="" src="images/spinner2.gif"></div>
<!--=================================================== HEADER  ===================================================-->
<?php echo $this->partial('layout/header')?>
<!--=================================================== END HEADER  ===================================================-->
<?php echo $this->content?>
<!--=================================================== FOOTER  ===================================================-->
<?php echo $this->partial('layout/footer')?>
<!--=================================================== END FOOTER  ===================================================-->
        
        
        
        
          <script src="js/bootstrap.min.js"></script>
        <script src="js/jquery.bxslider/jquery.bxslider.min.js"></script>
        <script src="js/pagination/jquery.twbsPagination.min.js"></script>
        <script src="js/alertify.js/alertify.min.js"></script>
        <script src="js/main.js"></script>
        
        
    </body>
</html>
        